In [1]:
!pip install -q langchain-community pypdf

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 13.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 33.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 2.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [2]:
import re
import pandas as pd
import os
import io

from google.colab import auth
from googleapiclient.discovery import build
from google.auth import default
from googleapiclient.http import MediaIoBaseDownload

FILE_ID = "1ZfMR_y92P6stVVupl1QGykcknl6EJU8X"
pdf_path = "/content/npr-7150-2d.pdf"

if not os.path.exists(pdf_path):
    auth.authenticate_user()

    creds, _ = default()
    drive = build("drive", "v3", credentials=creds)

    request = drive.files().get_media(
        fileId=FILE_ID,
        supportsAllDrives=True
    )

    with io.FileIO(pdf_path, "wb") as f:
        downloader = MediaIoBaseDownload(f, request)

        done = False
        while not done:
            status, done = downloader.next_chunk()
            print(f"Downloaded {int(status.progress() * 100)}%")

    print(f"PDF downloaded to: {pdf_path}")

else:
    print(f"PDF already exists at: {pdf_path}")

WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.
WARNING:google_auth_httplib2:httplib2 transport does not support per-request timeout. Set the timeout when constructing the httplib2.Http instance.

Downloaded 100%
PDF downloaded to: /content/npr-7150-2d.pdf

In [3]:
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader(pdf_path)
pages = loader.load()

print(f"Loaded {len(pages)} pages")

/tmp/ipykernel_2907/3021515166.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader

Loaded 89 pages

## Exploration of NPR 7150.2D Structure

Before transforming the standard into individual SWE requirements,
we examine the original document structure to determine which
information should be retained for downstream retrieval and auditing.

### 1. Inspect Raw PDF Extraction

We first inspect several pages from the original PDF extraction to understand
the document structure and identify repeated metadata, headings, notes,
requirements, and other patterns that may affect parsing.

In [4]:
for page_num in [0, 10, 19, 34, 45]:
    print("=" * 80)
    print(f"PAGE {page_num + 1}")
    print("=" * 80)
    print(pages[page_num].page_content[:2500])
    print()

================================================================================
PAGE 1
================================================================================
| NODIS Library | Program Formulation(7000s) | Search |
 NASA
Procedural
Requirements
NPR 7150.2D
Effective Date: March 08, 2022
Expiration Date: March 08, 2027
COMPLIANCE IS MANDATORY FOR NASA EMPLOYEES
NASA Software Engineering Requirements
Responsible Office: Office of the Chief Engineer
Table of Contents
Preface
P.1 Purpose
P.2 Applicability
P.3 Authority
P.4 Applicable Documents and Forms
P.5 Measurement/Verification
P.6 Cancellation
Chapter 1. Introduction
1.1 Overview
1.2 Hierarchy of NASA Software-Related Engineering and Program/Project Documents
1.3 Document Structure
Chapter 2. Roles, Responsibilities, and Principles Related to
Tailoring of the Requirements
2.1 Roles and Responsibilities
2.2 Principles Related to Tailoring of the Requirements
Chapter 3. Software Management Requirements
3.1 Software Life Cycle Planning
3.2 Software Cost Estimation
3.3 Software Schedules
3.4 Software Training
NPR 7150.2D -- TOC
This document does not bind the public, except as authorized by law or as
incorporated into a contract. This document is uncontrolled when printed. Check
the NASA Online Directives Information System (NODIS) Library to verify that
this is the correct version before use: https://nodis3.gsfc.nasa.gov.
Page  1  of  89
NPR 7150.2D -- TOC Page  1  of  89

================================================================================
PAGE 11
================================================================================
Chapter 2. Roles, Responsibilities, and
Principles Related to Tailoring of the
Requirements
2.1 Roles and Responsibilities Associated with this Directive
2.1.1 The NASA Office of the Chief Engineer (OCE).
2.1.1.1 The NASA OCE shall lead and maintain a NASA Software Engineering Initiative to advance
software engineering practices. [SWE-002]
2.1.1.2 The NASA OCE shall periodically benchmark each Center’s software engineering capability
against requirements in this directive. [SWE-004]
Note: Capability Maturity Model® Integration (CMMI®) for Development (CMMI®-DEV)
appraisals are the preferred benchmarks for objectively measuring progress toward
software engineering process improvement at NASA Centers.
2.1.1.3 The NASA OCE shall periodically review the project requirements mapping matrices.
[SWE-152]
2.1.1.4 The NASA OCE shall authorize appraisals against selected requirements in this NPR to
check compliance. [SWE-129]
2.1.1.5 The NASA OCE and Center training organizations shall provide training to advance
software engineering practices. [SWE-100]
2.1.1.6 The NASA OCE shall maintain an Agency-wide process asset library of applicable best
practices and process templates for all size projects. [SWE-098]
2.1.2 NASA Chief, Safety and Mission Assurance (SMA).
2.1.2.1 The NASA Chief, SMA manages Agency software assurance policy and software safety
policies and is the Technical Authority (TA) for any requirements in this directive.
2.1.2.2 The NASA Chief, SMA shall lead and maintain a NASA Software Assurance and Software
Safety Initiative to advance software assurance and software safety practices. [SWE-208]
2.1.2.3 The NASA Chief, SMA shall periodically benchmark each Center’s software assurance and
software safety capabilities against the NASA-STD-8739.8, NASA Software Assurance and
Software Safety Standard. [SWE-209]
2.1.2.4 The NASA Chief, SMA shall periodically review the project’s requirements mapping
matrices. [SWE-212]
2.1.2.5 The NASA Chief, SMA shall authorize appraisals against selected requirements in this NPR
to check compliance. [SWE-221]
NPR 7150.2D -- Chapter2
This document does not bind the public, except as authorized by law or as
incorporated into a contract. This document is uncontrolled when printed. Check
the NASA Online Directives Information System (NODIS) Library to verify that
this is the correct version before use: https://nodis3.gsfc.nasa.gov.
Page  11  of  89
NPR 7150.2D -- Chapter2 Page  11  of  89

================================================================================
PAGE 20
================================================================================
Chapter 3: Software Management
Requirements
3.1 Software Life Cycle Planning
3.1.1 Software life cycle planning covers the software aspects of a project from inception through
retirement. The software life cycle planning is an organizing process that considers the software as a
whole and provides the planning activities required to ensure a coordinated, well-engineered process
for defining and implementing project activities. These processes, plans, and activities are
coordinated within the project. At project conception, software needs for the project are analyzed,
including acquisition, supply, development, operation, maintenance, retirement, decommissioning,
and supporting activities and processes. The software effort is scoped, the development processes
defined, measurements defined, and activities are documented in software planning documents.
3.1.2 The project manager shall assess options for software acquisition versus development.
[SWE-033]
Note: The assessment can include risk, cost, and benefits criteria for each of the options
listed below:
a. Acquire an off-the-shelf software product that satisfies the requirement.
b. Develop a software product or obtain the software service internally.
c. Develop the software product or obtain the software service through contract.
d. Enhance an existing software product or service.
e. Reuse an existing software product or service.
f. Source code available external to NASA.
See the NASA Software Engineering Handbook for additional detail.
3.1.3 The project manager shall develop, maintain, and execute software plans, including security
plans, that cover the entire software life cycle and, as a minimum, address the requirements of this
directive with approved tailoring. [SWE-013]
Note: The recommended practices and guidelines for the content of different types of
software planning activities (whether stand-alone or condensed into one or more project
level or software documents or electronic files) are defined in NASA-HDBK-2203. The
project should include, or reference in the software development plans, procedures for
coordinating the software development and design, and the system or project development
life cycle.
3.1.4 The project manager shall track the actual results and performance of software activities
NPR 7150.2D -- Chapter3
This document does not bind the public, except as authorized by law or as
incorporated into a contract. This document is uncontrolled when printed. Check
the NASA Online

================================================================================
PAGE 35
================================================================================
Note: For safety critical software, the unit testing should follow the requirement
established in 3.7.4 of this document.
4.4.6 The project manager shall assure that the unit test results are repeatable. [SWE-186]
4.4.7 The project manager shall provide a software version description for each software release.
[SWE-063]
4.4.8 The project manager shall validate and accredit the software tool(s) required to develop or
maintain software. [SWE-136]
Note: All software development tools contain some number of software defects. Validation
and accreditation of the critical software development and maintenance tools ensure that
the tools being used during the software development life cycle do not generate or insert
errors in the software executable components. Software tool accreditation is the
certification that a software tool is acceptable for use for a specific purpose. Accreditation
is conferred by the organization best positioned to make the judgment that the software tool
in question is acceptable. The likelihood that work products will function properly is
enhanced, and the risk of error is reduced if the tools used in the development and
maintenance processes have been validated and accredited themselves.
4.5 Software Testing
4.5.1 The purpose of testing is to verify the software functionality and remove defects. Testing
verifies the code against the requirements and the design to ensure that the requirements are
implemented. Testing also identifies problems and defects that are corrected and tracked to closure
before product delivery. Testing also validates that the software operates appropriately in the
intended environment. Please note for Class A software there are additional software test
requirements and software integration requirements as defined in NPR 8705.2.
4.5.2 The project manager shall establish and maintain: [SWE-065]
a. Software test plan(s).
b. Software test procedure(s).
c. Software test(s), including any code specifically written to perform test procedures.
d. Software test report(s).
4.5.3 The project manager shall test the software against its requirements. [SWE-066]
Note: A best practice for Class A, B, and C software projects is to have formal software
testing planned, conducted, witnessed, and approved by an independent organization
outside of the development team.
4.5.4 The project manager shall place software items under configuration management prior to
testing. [SWE-187]
NPR 7150.2D -- Chapter4
This document does

================================================================================
PAGE 46
================================================================================
Appendix A. Definitions
Accredit. The official acceptance of a software development tool, model, or simulation (including
associated data) to use for a specific purpose.
Analysis. The post-processing or interpretation of the individual values, arrays, files of data, or
execution information. It is a careful study of something to learn about its parts, what they do, and
how they are related to each other.
Assure. When personnel makes certain that the specified software engineering, software
management, and software assurance activities have been performed by others.
Bidirectional Traceability. Association among two or more logical entities that are discernible in
either direction (to and from an entity). (ISO/IEC/IEEE 24765, Systems and software engineering –
Vocabulary)
Code coverage. The percentage of the software that has been executed (covered) by the test suite.
Commercial Off-the-Shelf Software (COTS). The software product is available for purchase and
use without the need to conduct development activities. COTS solutions, as opposed to
custom-developed solutions, are typically readily available in the commercial marketplace and ready
for use as purchased.
Computer. A functional unit that can perform substantial computations, including numerous
arithmetic operations and logic operations.
Computer Software Configuration Item. An aggregation of software that is designated for
configuration management and treated as a single entity in the configuration management process.
Computer System. A system containing one or more computers and associated software. (Source:
ISO/IEC/IEEE 24765)
Condition. (1) Measurable qualitative or quantitative attribute that is stipulated for a requirement
and that indicates a circumstance or event under which a requirement applies (Systems and software
engineering--Systems and software assurance--Part 1: Concepts and vocabulary ISO/IEC/IEEE
15026-1:2019, 3.1.5), (2) Description of a contingency to be considered in the representation of a
problem or a reference to other procedures to be considered as part of the condition (Information
processing -- Specification of single-hit decision tables, ISO 5806:1984, 3.6), and (3) Boolean
expression containing no Boolean operators (Software and systems engineering -- Software testing
-- Part 4: Test techniques, ISO/IEC/IEEE 29119-4:2015, 4.6).
Contracted Software. Software created for a project by a contractor or subcontractor.
Cybersecurity. The protection of information and i

### 2. Identify Common Document Structures

The standard contains multiple forms of structured information. We inspect
their frequency before deciding what should be preserved in the final dataset.

In [5]:
raw_text = "\n".join(page.page_content for page in pages)

patterns = {
    "SWE requirement IDs": r"\[SWE-\d+\]",
    "Notes": r"\bNote:",
    "Chapter headings": r"(?m)^Chapter\s+\d+",
    "Numbered sections": r"(?m)^\d+\.\d+(?:\.\d+)*\s+",
    "Lettered subclauses": r"(?m)^[a-z]\.\s+",
    "Numbered subclauses": r"(?m)^\(\d+\)\s+"
}

for name, pattern in patterns.items():
    matches = re.findall(pattern, raw_text)
    print(f"{name}: {len(matches)}")

SWE requirement IDs: 130
Notes: 57
Chapter headings: 12
Numbered sections: 380
Lettered subclauses: 307
Numbered subclauses: 22

### 3. Inspect Chapter Organization

NPR 7150.2D is organized by chapter and section. Since later
retrieval may originate from chapter-level context, we inspect and preserve
this hierarchy.

In [6]:
chapter_pattern = re.compile(
    r"(?m)^Chapter\s+(\d+)[:.]\s*(.*)"
)

chapter_matches = chapter_pattern.findall(raw_text)

for chapter_num, title in chapter_matches:
    print(f"Chapter {chapter_num}: {title}")

Chapter 1: Introduction
Chapter 2: Roles, Responsibilities, and Principles Related to
Chapter 3: Software Management Requirements
Chapter 4: Software Engineering (Life Cycle) Requirements
Chapter 5: Supporting Software Life Cycle Requirements
Chapter 6: Recommended Software Documentation Contents
Chapter 1: Introduction
Chapter 2: Roles, Responsibilities, and
Chapter 3: Software Management
Chapter 4: Software Engineering Life Cycle
Chapter 5: Supporting Software Life Cycle
Chapter 6: Recommended Software Records

The raw extraction contains duplicate chapter headings because the Table of
Contents and chapter body headings are both present. Some titles also span
multiple PDF lines. These will be normalized during transformation.

### 4. Text Cleaning and Page Preservation

The PDF text contains repeated headers, footers, page numbers, and document metadata.
These are removed before exploration so they do not interfere with section detection
or requirement extraction. Page boundaries are preserved so extracted clauses can
still be traced back to their source page

In [7]:
full_text = ""
page_ranges = []

for page_num, page in enumerate(pages, start=1):
    text = page.page_content

    text = re.sub(
        r"NPR 7150\.2D -- [^\n]+\n"
        r"This document does not bind the public.*?"
        r"Page\s+\d+\s+of\s+\d+",
        "",
        text,
        flags=re.DOTALL
    )

    text = re.sub(
        r"NPR 7150\.2D -- [^\n]+ Page\s+\d+\s+of\s+\d+",
        "",
        text
    )

    start = len(full_text)

    full_text += text.strip() + "\n\n"

    end = len(full_text)

    page_ranges.append({
        "page": page_num,
        "start": start,
        "end": end
    })

print(full_text[:2000])

| NODIS Library | Program Formulation(7000s) | Search |
 NASA
Procedural
Requirements
NPR 7150.2D
Effective Date: March 08, 2022
Expiration Date: March 08, 2027
COMPLIANCE IS MANDATORY FOR NASA EMPLOYEES
NASA Software Engineering Requirements
Responsible Office: Office of the Chief Engineer
Table of Contents
Preface
P.1 Purpose
P.2 Applicability
P.3 Authority
P.4 Applicable Documents and Forms
P.5 Measurement/Verification
P.6 Cancellation
Chapter 1. Introduction
1.1 Overview
1.2 Hierarchy of NASA Software-Related Engineering and Program/Project Documents
1.3 Document Structure
Chapter 2. Roles, Responsibilities, and Principles Related to
Tailoring of the Requirements
2.1 Roles and Responsibilities
2.2 Principles Related to Tailoring of the Requirements
Chapter 3. Software Management Requirements
3.1 Software Life Cycle Planning
3.2 Software Cost Estimation
3.3 Software Schedules
3.4 Software Training

3.4 Software Training
3.5 Software Classification Assessments
3.6 Software Assurance and Software Independent Verification & Validation
3.7 Safety-Critical Software
3.8 Automatic Generation of Software Source Code
3.9 Software Development Processes and Practices
3.10 Software Reuse
3.11 Software Cybersecurity
3.12 Software Bi-Directional Traceability
Chapter 4. Software Engineering (Life Cycle) Requirements
4.1 Software Requirements
4.2 Software Architecture
4.3 Software Design
4.4 Software Implementation
4.5 Software Testing
4.6 Software Operations, Maintenance, and Retirement
Chapter 5. Supporting Software Life Cycle Requirements
5.1 Software Configuration Management
5.2 Software Risk Management
5.3 Software Peer Reviews/Inspections
5.4 Software Measurements
5.5 Software Non-conformance or Defect Management
Chapter 6. Recommended Software Documentation Contents
6.1 Software Engineering Products
6.2 Software Engineering Product Content
Appendix A. Definitions
Appendix B. Acronyms
Appendix C. Requirements Mapping Matrix
Appendix D. Software Classificat

### 5. Validate Cleaned Text

After removing repeated headers and footers, we inspect the cleaned text to
confirm that meaningful chapter, section, requirement, note, and subclause
content has been preserved.

In [8]:
print(full_text[full_text.find("Chapter 3:"):full_text.find("Chapter 3:") + 3000])

Chapter 3: Software Management
Requirements
3.1 Software Life Cycle Planning
3.1.1 Software life cycle planning covers the software aspects of a project from inception through
retirement. The software life cycle planning is an organizing process that considers the software as a
whole and provides the planning activities required to ensure a coordinated, well-engineered process
for defining and implementing project activities. These processes, plans, and activities are
coordinated within the project. At project conception, software needs for the project are analyzed,
including acquisition, supply, development, operation, maintenance, retirement, decommissioning,
and supporting activities and processes. The software effort is scoped, the development processes
defined, measurements defined, and activities are documented in software planning documents.
3.1.2 The project manager shall assess options for software acquisition versus development.
[SWE-033]
Note: The assessment can include risk, cost, and benefits criteria for each of the options
listed below:
a. Acquire an off-the-shelf software product that satisfies the requirement.
b. Develop a software product or obtain the software service internally.
c. Develop the software product or obtain the software service through contract.
d. Enhance an existing software product or service.
e. Reuse an existing software product or service.
f. Source code available external to NASA.
See the NASA Software Engineering Handbook for additional detail.
3.1.3 The project manager shall develop, maintain, and execute software plans, including security
plans, that cover the entire software life cycle and, as a minimum, address the requirements of this
directive with approved tailoring. [SWE-013]
Note: The recommended practices and guidelines for the content of different types of
software planning activities (whether stand-alone or condensed into one or more project
level or software documents or electronic files) are defined in NASA-HDBK-2203. The
project should include, or reference in the software development plans, procedures for
coordinating the software development and design, and the system or project development
life cycle.
3.1.4 The project manager shall track the actual results and performance of software activities

3.1.4 The project manager shall track the actual results and performance of software activities
against the software plans. [SWE-024]
a. Corrective actions are taken, recorded, and managed to closure.
b. Changes to commitments (e.g., software plans) that have been agreed to by the affected groups
and individuals are taken, recorded, and managed.
3.1.5 The project manager shall define and document the acceptance criteria for the software.
[SWE-034]
3.1.6 The project manager shall establish and maintain the software processes, software
documentation plans, list of developed electronic products, deliverables, and list of tasks for the
software development that are required for the pr

In [9]:
print("Raw characters:", len(raw_text))
print("Cleaned characters:", len(full_text))
print("Characters removed:", len(raw_text) - len(full_text))

Raw characters: 212308
Cleaned characters: 178054
Characters removed: 34254

In [10]:
section_pattern = re.compile(
    r"(?m)^([2-5]\.\d+(?:\.\d+)*)\s+"
)

section_matches = list(section_pattern.finditer(full_text))

print(f"Found {len(section_matches)} numbered sections")

Found 351 numbered sections

In [11]:
for match in section_matches[:20]:
    print(match.group(1), "->", full_text[match.start():match.start() + 150].replace("\n", " "))

2.1 -> 2.1 Roles and Responsibilities  2.2 Principles Related to Tailoring of the Requirements  Chapter 3. Software Management Requirements 3.1 Software Life
2.2 -> 2.2 Principles Related to Tailoring of the Requirements  Chapter 3. Software Management Requirements 3.1 Software Life Cycle Planning 3.2 Software Cos
3.1 -> 3.1 Software Life Cycle Planning 3.2 Software Cost Estimation 3.3 Software Schedules 3.4 Software Training  3.4 Software Training 3.5 Software Classif
3.2 -> 3.2 Software Cost Estimation 3.3 Software Schedules 3.4 Software Training  3.4 Software Training 3.5 Software Classification Assessments 3.6 Software
3.3 -> 3.3 Software Schedules 3.4 Software Training  3.4 Software Training 3.5 Software Classification Assessments 3.6 Software Assurance and Software Indepe
3.4 -> 3.4 Software Training  3.4 Software Training 3.5 Software Classification Assessments 3.6 Software Assurance and Software Independent Verification & Va
3.4 -> 3.4 Software Training 3.5 Software Classification Assessments 3.6 Software Assurance and Software Independent Verification & Validation 3.7 Safety-Cri
3.5 -> 3.5 Software Classification Assessments 3.6 Software Assurance and Software Independent Verification & Validation 3.7 Safety-Critical Software 3.8 Aut
3.6 -> 3.6 Software Assurance and Software Independent Verification & Validation 3.7 Safety-Critical Software 3.8 Automatic Generation of Software Source Cod
3.7 -> 3.7 Safety-Critical Software 3.8 Automatic Generation of Software Source Code 3.9 Software Development Processes and Practices  3.10 Software Reuse  3
3.8 -> 3.8 Automatic Generation of Software Source Code 3.9 Software Development Processes and Practices  3.10 Software Reuse  3.11 Software Cybersecurity 3.
3.9 -> 3.9 Software Development Processes and Practices  3.10 Software Reuse  3.11 Software Cybersecurity 3.12 Software Bi-Directional Traceability  Chapter
3.10 -> 3.10 Software Reuse  3.11 Software Cybersecurity 3.12 Software Bi-Directional Traceability  Chapter 4. Software Engineering (Life Cycle) Requirements
3.11 -> 3.11 Software Cybersecurity 3.12 Software Bi-Directional Traceability  Chapter 4. Software Engineering (Life Cycle) Requirements 4.1 Software Requirem
3.12 -> 3.12 Software Bi-Directional Traceability  Chapter 4. Software Engineering (Life Cycle) Requirements 4.1 Software Requirements 4.2 Software Architectu
4.1 -> 4.1 Software Requirements 4.2 Software Architecture 4.3 Software Design 4.4 Software Implementation 4.5 Software Testing 4.6 Software Operations, Main
4.2 -> 4.2 Software Architecture 4.3 Software Design 4.4 Software Implementation 4.5 Software Testing 4.6 Software Operations, Maintenance, and Retirement  C
4.3 -> 4.3 Software Design 4.4 Software Implementation 4.5 Software Testing 4.6 Software Operations, Maintenance, and Retirement  Chapter 5. Supporting Softw
4.4 -> 4.4 Software Implementation 4.5 Software Testing 4.6 Software Operations, Maintenance, and Retirement  Chapter 5. Supporting Software Life Cycle Requi
4.5 -> 4.5 Software Testing 4.6 Software Operations, Maintenance, and Retirement  Chapter 5. Supporting Software Life Cycle Requirements 5.1 Software Configu

In [12]:
def get_page_number(offset):
    for page_info in page_ranges:
        if page_info["start"] <= offset < page_info["end"]:
            return page_info["page"]

    return None

In [13]:
pd.set_option("display.max_colwidth", 200)

### 6. Inspect Representative Sections

Not every numbered section has the same structure. Some contain a single SWE
requirement, while others include notes, lists, or nested conditions. We inspect
examples before reducing the document into requirement-level records.

In [14]:
examples = ["2.1.5.10", "3.1.14", "4.5.3", "4.5.9"]

for section_id in examples:
    match = next(
        m for m in section_matches
        if m.group(1) == section_id
        and get_page_number(m.start()) > 10
    )

    start = match.start()

    later_matches = [
        m for m in section_matches
        if m.start() > start
    ]

    end = later_matches[0].start() if later_matches else len(full_text)

    print("=" * 80)
    print("SECTION:", section_id)
    print("=" * 80)
    print(full_text[start:end][:1500])

================================================================================
SECTION: 2.1.5.10
================================================================================
2.1.5.10 For Class A, B, and C software projects, each Center Director, or designee, shall establish
and maintain software cost repository(ies) that contains at least the following measures: [SWE-142]

a. Planned and actual effort and cost.
b. Planned and actual schedule dates for major milestones.
c. Both planned and actual values for key cost parameters that typically include software size,
requirements count, defects counts for maintenance or sustaining engineering projects, and cost
model inputs.
d. Project descriptors or metadata that typically includes software class, software domain/type, and
requirements volatility.

================================================================================
SECTION: 3.1.14
================================================================================
3.1.14 The project manager shall satisfy the following conditions when a COTS, GOTS, MOTS,
OSS, or reused software component is acquired or used: [SWE-027]
a. The requirements to be met by the software component are identified.
b. The software component includes documentation to fulfill its intended purpose (e.g., usage
instructions).
c. Proprietary rights, usage rights, ownership, warranty, licensing rights, transfer rights, and
conditions of use (e.g., required copyright, author, and applicable license notices within the software
code, or a requirement to redistribute the licensed software only under the same license (e.g., GNU
GPL, ver. 3, license)) have been addressed and coordinated with Center Intellectual Property
Counsel.
d. Future support for the software product is planned and adequate for project needs.
e. The software component is verified and validated to the same level required to accept a similar
developed software component for its intended use.
f. The project has a plan to perform periodic assessments of vendor reported defects to ensure the
defects do not impact the selected software components.

Note: The project responsible for procuring off-the-shelf software is responsible for
documenting, prior to procurement, a plan for verifying and validating the software to the
same level that would be required for a developed software component. The project ensures
that the COTS, GOTS, MOTS, reused, and auto-generated code software components and
data meet th
================================================================================
SECTION: 4.5.3
================================================================================
4.5.3 The project manager shall test the software against its requirements. [SWE-066]
Note: A best practice for Class A, B, and C software projects is to have formal software
testing planned, conducted, witnessed, and approved by an independent organization
outside of the development team.

================================================================================
SECTION: 4.5.9
================================================================================
4.5.9 The project manager shall ensure that the code coverage measurements for the software are
selected, implemented, tracked, recorded, and reported. [SWE-189]
Note: This requirement can be met by running unit, integration, and validation tests;
measuring the code coverage; and achieving the code coverage by additional (requirement
based) tests, inspection, or analysis.
If the project does not get 100 percent structural coverage, it means one of four things and each
requires action on the project manager’s part:
• Requirement missing - the code that hasn’t been covered is performing an essential activity, but no
requirement indicates that this should be done;
• Test missing - the code that hasn’t been covered relates to an existing requirement, but no test was
implemented for it;
• Extraneous/dead code – the code that hasn’t been covered is not traceable to any requirement and
isn’t needed by the software;
• Deactivated code - the code that hasn’t been covered isn’t traceable to any requirements for the
current system, but is intended to be executed in specific configurations.

current system, but is intended to be executed in specific configurations.
The code coverage data and any rationale for uncovered code should be presented and reviewed at
major project milestones.

Inspection of representative sections revealed occasional duplicated text at
PDF page boundaries. For example, part of the explanatory text associated with
SWE-189 appears twice after extraction. This indicates that additional
page-boundary cleanup may be necessary before the parsed text is used for
retrieval.

## Structured SWE Requirement Dataset

Based on the document exploration above, individual SWE requirements are used
as the primary records for the initial dataset. Chapter, section, and page
metadata are retained for traceability and later retrieval.

In [15]:
rows = []

for i, match in enumerate(section_matches):
    section = match.group(1)

    start = match.end()

    if i + 1 < len(section_matches):
        end = section_matches[i + 1].start()
    else:
        end = len(full_text)

    block_text = full_text[start:end].strip()

    swe_match = re.search(r"\[SWE-(\d+)\]", block_text)

    if not swe_match:
        continue

    swe_id = f"SWE-{swe_match.group(1)}"

    requirement_text = re.sub(
        r"\[SWE-\d+\]",
        "",
        block_text
    ).strip()

    requirement_text = re.split(
        r"\nChapter\s+\d+[:.]",
        requirement_text
    )[0].strip()

    page = get_page_number(match.start())

    rows.append({
        "swe_id": swe_id,
        "section": section,
        "requirement_text": requirement_text,
        "page": page
    })

requirements_df = pd.DataFrame(rows)

print(f"Found {len(requirements_df)} SWE requirements")
print("Total rows:", len(requirements_df))
print("Unique SWE IDs:", requirements_df["swe_id"].nunique())
print("Unique sections:", requirements_df["section"].nunique())

Found 130 SWE requirements
Total rows: 130
Unique SWE IDs: 130
Unique sections: 130

In [16]:
requirements_df.isna().sum()

swe_id              0
section             0
requirement_text    0
page                0
dtype: int64

In [17]:
requirements_df[
    requirements_df["swe_id"].duplicated(keep=False)
]

Empty DataFrame
Columns: [swe_id, section, requirement_text, page]
Index: []

In [18]:
requirements_df

,swe_id,section,requirement_text,page
0,SWE-002,2.1.1.1,The NASA OCE shall lead and maintain a NASA Software Engineering Initiative to advance\nsoftware engineering practices.,11
1,SWE-004,2.1.1.2,The NASA OCE shall periodically benchmark each Center’s software engineering capability\nagainst requirements in this directive. \nNote: Capability Maturity Model® Integration (CMMI®) for Develop...,11
2,SWE-152,2.1.1.3,The NASA OCE shall periodically review the project requirements mapping matrices.,11
3,SWE-129,2.1.1.4,The NASA OCE shall authorize appraisals against selected requirements in this NPR to\ncheck compliance.,11
4,SWE-100,2.1.1.5,The NASA OCE and Center training organizations shall provide training to advance\nsoftware engineering practices.,11
...,...,...,...,...
125,SWE-200,5.4.6,"The project manager shall collect, track, and report software requirements volatility metrics.",42
126,SWE-201,5.5.1,The project manager shall track and maintain software non-conformances (including defects in\ntools and appropriate ground software).,42
127,SWE-202,5.5.2,"The project manager shall define and implement clear software severity levels for all software\nnon-conformances (including tools, COTS, GOTS, MOTS, OSS, reused software components, and\napplicabl...",42
128,SWE-203,5.5.3,"The project manager shall implement mandatory assessments of reported non-conformances\nfor all COTS, GOTS, MOTS, OSS, and/or reused software components. \n\nNote: This includes operating systems,...",42
129,SWE-204,5.5.4,The project manager shall implement process assessments for all high-severity software\nnon-conformances (closed loop process).,43

In [19]:
requirements_df["chapter"] = (
    requirements_df["section"]
    .str.split(".")
    .str[0]
)

requirements_df["chapter"].value_counts().sort_index()

chapter
2    30
3    45
4    34
5    21
Name: count, dtype: int64

In [20]:
requirements_df["section_group"] = (
    requirements_df["section"]
    .str.extract(r"^(\d+\.\d+)")[0]
)

requirements_df.groupby(
    ["chapter", "section_group"]
).size()

chapter  section_group
2        2.1              28
         2.2               2
3        3.1              13
         3.10              2
         3.11              7
         3.12              1
         3.2               3
         3.3               3
         3.4               1
         3.5               2
         3.6               5
         3.7               5
         3.8               2
         3.9               1
4        4.1               6
         4.2               2
         4.3               1
         4.4               7
         4.5              13
         4.6               5
5        5.1               8
         5.2               1
         5.3               3
         5.4               5
         5.5               4
dtype: int64

In [22]:
requirements_df["word_count"] = (
    requirements_df["requirement_text"]
    .str.split()
    .str.len()
)

requirements_df["word_count"].describe()

count    130.000000
mean      63.015385
std       69.136085
min       10.000000
25%       20.250000
50%       38.000000
75%       85.000000
max      412.000000
Name: word_count, dtype: float64

In [23]:
requirements_df.nlargest(
    10,
    "word_count"
)[
    ["swe_id", "section", "page", "word_count", "requirement_text"]
]

,swe_id,section,page,word_count,requirement_text
25,SWE-214,2.1.5.16,14,412,"The Center Director or designee (e.g., the Civil Servant Technical POC for the software\nproduct) shall perform the following actions for each type of internal NASA software transfer or\nreuse: \..."
27,SWE-126,2.1.8.2,16,374,The technical and institutional authorities for requirements in this directive shall: \na. Assess projects’ requirements mapping matrices and tailoring from requirements in this directive\nby:\n\...
64,SWE-032,3.9.2,28,305,"The project manager shall acquire, develop, and maintain software from an organization with a\nnon-expired CMMI®-DEV rating as measured by a CMMI® Institute Certified Lead Appraiser as\nfollows: ..."
66,SWE-148,3.10.2,29,297,The project manager shall evaluate software for potential reuse by other projects across\nNASA and contribute reuse candidates to the appropriate NASA internal sharing and reuse software\nsystem. ...
42,SWE-027,3.1.14,22,236,"The project manager shall satisfy the following conditions when a COTS, GOTS, MOTS,\nOSS, or reused software component is acquired or used: \na. The requirements to be met by the software compone..."
59,SWE-134,3.7.3,26,216,"If a project has safety-critical software or mission-critical software, the project manager shall\nimplement the following items in the software: \na. The software is initialized, at first start ..."
98,SWE-189,4.5.9,36,201,"The project manager shall ensure that the code coverage measurements for the software are\nselected, implemented, tracked, recorded, and reported. \nNote: This requirement can be met by running u..."
50,SWE-020,3.5.1,24,177,"The project manager shall classify each system and subsystem containing software in\naccordance with the highest applicable software classification definitions for Classes A, B, C, D, E,\nand F so..."
41,SWE-125,3.1.13,22,171,"Each project manager with software components shall maintain a requirements mapping\nmatrix or multiple requirements mapping matrices against requirements in this NPR, including those\ndelegated t..."
16,SWE-006,2.1.5.6,13,144,"Center Director, or designee, shall maintain a reliable list of their Center’s programs and\nprojects containing Class A, B, C, and D software. The list should include: \na. Project/program name ..."

Exploration of NPR 7150.2D shows that the document is hierarchical rather
than a flat list of requirements. In addition to 130 SWE requirement IDs,
the standard contains chapter and section headings, explanatory notes,
lettered and numbered subclauses, and other supporting context.

Based on these findings, we retain chapter, section, page, and parent-section
metadata alongside individual SWE requirements. Larger section-level text
blocks are also preserved for downstream retrieval because some compliance
decisions may require context beyond an isolated SWE statement.

Manual inspection also identified occasional PDF extraction artifacts at page
boundaries, which will require additional cleanup or validation.