# RAG audit demonstration

Connect FAISS retrieval to a structured NASA requirement audit. The saved outputs come from the local model run documented below. Set `RUN_MODEL = True` to rerun inference. Schema and citation validity do not establish verdict accuracy.

In Colab, choose a GPU runtime, then run all cells. Setup downloads the public repository and installs dependencies. Locally, open this notebook from the checkout after installing `requirements.txt`.

In [1]:
from pathlib import Path
import subprocess
import sys

IN_COLAB = "google.colab" in sys.modules
if IN_COLAB:
    ROOT = Path("/content/Aerospace-1C-compliance-copilot")
    if not ROOT.exists():
        subprocess.run(["git", "clone", "--branch", "alan/rag-audit-pipeline",
                        "https://github.com/Break-Through-Tech/Aerospace-1C-compliance-copilot.git",
                        str(ROOT)], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", str(ROOT / "requirements.txt")], check=True)
else:
    ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "compliance_copilot").is_dir())
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
print("Repository ready")

Repository ready

In [2]:
RUN_MODEL = False
REPORT = ROOT / "outputs/rag/demo.json"
if RUN_MODEL:
    REPORT = ROOT / "outputs/rag/notebook-run.json"
    REPORT.unlink(missing_ok=True)
    completed = subprocess.run([sys.executable, str(ROOT / "scripts/run_rag_demo.py"),
                                "--output", str(REPORT)], cwd=ROOT)
    if not REPORT.exists():
        raise RuntimeError("Model run failed before writing results; inspect the output above")
    if completed.returncode:
        print("The run contains audit errors; inspect them below.")
print("Displaying a new run" if RUN_MODEL else "Displaying the saved model run")

Displaying the saved model run

In [3]:
import json
import pandas as pd
from compliance_copilot.schemas import AuditResult

report = json.loads(REPORT.read_text())
results = [AuditResult.model_validate(row) for row in report["results"]]
print(json.dumps(report["config"], indent=2))
pd.DataFrame([{"requirement_id": r.requirement_id, "status": r.status,
               "verdict": r.audit.verdict if r.audit else None,
               "cited_swe_ids": ", ".join(c.swe_id for c in r.audit.citations) if r.audit else "",
               "error": r.error_code} for r in results])

{
  "backend": "transformers",
  "model": "Qwen/Qwen3-4B-Instruct-2507",
  "model_revision": "cdbee75f17c01a7cc42f958dc650907174af0554",
  "embedding_model": "sentence-transformers/all-MiniLM-L6-v2",
  "embedding_revision": "1110a243fdf4706b3f48f1d95db1a4f5529b4d41",
  "top_k": 10,
  "normalize_agency": true,
  "do_sample": false,
  "max_new_tokens": 768,
  "device": "mps",
  "python": "3.12.13",
  "packages": {
    "torch": "2.14.1",
    "transformers": "4.57.6",
    "sentence-transformers": "5.7.0",
    "faiss-cpu": "1.15.1",
    "pydantic": "2.13.5"
  }
}

  requirement_id status  verdict              cited_swe_ids error
0    NASA-SR-001     ok    Meets           SWE-013, SWE-125  None
1    NASA-SR-002     ok      Gap           SWE-199, SWE-055  None
2    NASA-SR-003     ok    Meets           SWE-052, SWE-053  None
3    NASA-SR-004     ok    Meets                    SWE-050  None
4    NASA-SR-005     ok      Gap                    SWE-053  None
5    NASA-SR-006     ok    Meets                    SWE-055  None
6    NASA-SR-007     ok    Meets  SWE-057, SWE-081, SWE-083  None
7    NASA-SR-008     ok  Partial                    SWE-061  None
8    NASA-SR-009     ok    Meets           SWE-135, SWE-201  None
9    NASA-SR-010     ok    Meets           SWE-062, SWE-068  None

In [4]:
for result in results:
    print(result.requirement_id)
    print(result.requirement_text)
    if result.audit:
        print(result.audit.verdict + ": " + result.audit.reasoning)
        for citation in result.audit.citations:
            clause = next(c for c in result.retrieved if c.swe_id == citation.swe_id)
            print(citation.swe_id, citation.section, repr(citation.quote))
            print(clause.source_url)
    else:
        print(result.error_code, result.error_message)
    print()

NASA-SR-001
The NASA Project Manager shall develop, maintain, and execute a Software Development Plan and a Software Security Plan covering the full software life cycle from requirements through retirement, addressing every applicable requirement of NPR 7150.2D per the approved Requirements Mapping Matrix.
Meets: SWE-013 mandates development and execution of software plans covering the full life cycle and addressing NPR 7150.2D requirements with approved tailoring. SWE-125 requires a requirements mapping matrix to align with NPR requirements. The proposed requirement satisfies both by explicitly stating development, maintenance, execution of software and security plans, and reference to the approved mapping matrix.
SWE-013 3.1.3 '3.1.3 The project manager shall develop, maintain, and execute software plans, including security plans, that cover the entire software life cycle and, as a minimum, address the requirements of this directive with approved tailoring. [SWE-013]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=20
SWE-125 3.1.13 'Each project manager with software components shall maintain a requirements mapping matrix or multiple requirements mapping matrices against requirements in this NPR, including those delegated to other parties or accomplished by contract vehicles or Space Act Agreements.'
https://swehb.nasa.gov/spaces/SITE/pages/123601159/NPR%2B7150.2D

NASA-SR-002
The NASA software shall meet performance expectations as determined by the development team prior to delivery.
Gap: The proposed requirement states performance expectations are determined by the development team, but NASA requires the project manager to monitor and ensure performance meets or exceeds requirements, including constraints. The requirement lacks accountability to the project manager and omits verification against defined performance and functionality requirements. SWE-199 and SWE-055 mandate performance validation and monitoring, which are not addressed.
SWE-199 5.4.5 'The project manager shall monitor measures to ensure the software will meet or exceed performance and functionality requirements, including satisfying constraints.'
https://swehb.nasa.gov/spaces/SITE/pages/123601159/NPR%2B7150.2D
SWE-055 4.1.7 '4.1.7 The project manager shall perform requirements validation to ensure that the software will perform as intended in the customer environment. [SWE-055]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=32

NASA-SR-003
For Class B software, the NASA Project Manager shall perform, record, and maintain bidirectional traceability between higher-level and software requirements, software requirements and system hazards, software requirements and design components, design components and code, software requirements and software verifications, and software requirements and software non-conformances. The traceability records shall be updated within five business days of a requirement change.
Meets: SWE-052 mandates bidirectional traceability for Class B software across all specified pairs: higher-level to software requirements, software to hazards, design components, code, verification, and non-conformances. The requirement explicitly includes these traceability links and specifies update within five business days of change, aligning with SWE-053 on change tracking. No gaps or contradictions exist.
SWE-052 3.12.1 '3.12.1 The project manager shall perform, record, and maintain bi-directional traceability between the following software elements: [SWE-052] Table 1. Bi-directional traceability by software classification Bi-directional Traceability Class A, B, and C Class D Class F Higher-level requirements to the software requirements X X Software requirements to the system hazards X X Software requirements to the software design components X Software design components to the software code X Software requirements to the software verification(s) X X X Software requirements to the software non-conformances X X X'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=31
SWE-053 4.1.5 '4.1.5 The project manager shall track and manage changes to the software requirements. [SWE-053]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=32

NASA-SR-004
The NASA Project Manager shall establish, capture, record, approve, and maintain software requirements, including requirements for the reused GPS ephemeris library, in the DOORS requirements repository as part of the project technical specification.
Meets: SWE-050 mandates the project manager to establish, capture, record, approve, and maintain software requirements, including those for reused components, as part of the technical specification. The proposed requirement aligns fully with this obligation, specifically covering reused GPS ephemeris library requirements in the DOORS repository.
SWE-050 4.1.2 '4.1.2 The project manager shall establish, capture, record, approve, and maintain software requirements, including requirements for COTS, GOTS, MOTS, OSS, or reused software components, as part of the technical specification. [SWE-050]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=32

NASA-SR-005
Changes to NASA software requirements shall be logged in the issue tracker by the engineer making the change.
Gap: NASA SWE-053 mandates the project manager to track and manage changes, not the engineer. The proposed requirement shifts responsibility to the engineer, which contradicts the obligation.
SWE-053 4.1.5 '4.1.5 The project manager shall track and manage changes to the software requirements. [SWE-053]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=32

NASA-SR-006
The NASA Project Manager shall perform requirements validation with the customer, including scenario-based walkthroughs and a requirements review board, to confirm the software will perform as intended in the lunar relay operational environment prior to baselining.
Meets: SWE-055 mandates requirements validation to ensure software performs as intended in the customer environment; the proposed requirement aligns by specifying validation with the customer and scenario-based walkthroughs in the lunar relay environment, which is a specific instance of the customer environment. No mandatory obligations are missed or contradicted.
SWE-055 4.1.7 '4.1.7 The project manager shall perform requirements validation to ensure that the software will perform as intended in the customer environment. [SWE-055]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=32

NASA-SR-007
The NASA Project Manager shall transform the approved software requirements into a recorded software architecture, documented in the Software Architecture Description Document (SADD) and baselined under configuration management prior to detailed design.
Meets: SWE-057 mandates the project manager to transform software requirements into a recorded software architecture, which is directly covered by the proposed requirement. The mention of baselining under configuration management aligns with SWE-081 and SWE-083, which require identification and status recording of configuration items. No mandatory obligations are missing or contradicted.
SWE-057 4.2.3 '4.2.3 The project manager shall transform the requirements for the software into a recorded software architecture. [SWE-057]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=33
SWE-081 5.1.4 'The project manager shall identify the software configuration items (e.g., software records, code, data, tools, models, scripts) and their versions to be controlled for the project.'
https://swehb.nasa.gov/spaces/SITE/pages/123601159/NPR%2B7150.2D
SWE-083 5.1.6 'The project manager shall prepare and maintain records of the configuration status of software configuration items.'
https://swehb.nasa.gov/spaces/SITE/pages/123601159/NPR%2B7150.2D

NASA-SR-008
NASA software developers shall write clean, maintainable code following good engineering judgment.
Partial: SWE-061 mandates project managers to define and adhere to coding methods, standards, and criteria, which includes clean and maintainable code. The proposed requirement lacks specificity on how 'good engineering judgment' is defined or enforced, missing explicit adherence to formal standards. Thus, it partially meets the obligation.
SWE-061 4.4.3 '4.4.3 The project manager shall select, define, and adhere to software coding methods, standards, and criteria. [SWE-061]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=34

NASA-SR-009
The NASA Project Manager shall use static analysis tools during development and testing to analyze code for defects, software security, code coverage, and software complexity, and shall track identified findings to closure in the defect tracking system.
Meets: SWE-135 mandates static analysis for defects, security, coverage, and complexity during development and testing. The requirement covers these elements and includes tracking findings to closure, aligned with SWE-201 on tracking non-conformances. No gaps or contradictions exist.
SWE-135 4.4.4 '4.4.4 The project manager shall use static analysis tools to analyze the code during the development and testing phases to, at a minimum, detect defects, software security, code coverage, and software complexity. [SWE-135]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=34
SWE-201 5.5.1 '5.5.1 The project manager shall track and maintain software non-conformances (including defects in tools and appropriate ground software). [SWE-201]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=42

NASA-SR-010
The NASA Project Manager shall unit test each software code unit against its detailed design prior to integration, and shall record unit test results in the test management system.
Meets: SWE-062 mandates unit testing by the project manager, SWE-068 requires recording test evaluation, and the proposed requirement aligns with both by specifying unit testing against detailed design and recording results in the test management system. No mandatory obligations are missing or contradicted.
SWE-062 4.4.5 '4.4.5 The project manager shall unit test the software code. [SWE-062]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=34
SWE-068 4.5.5 '4.5.5 The project manager shall evaluate test results and record the evaluation. [SWE-068]'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=36

In [5]:
# Labels are joined only after inference, never supplied to the pipeline.
benchmark = pd.read_csv(ROOT / "data/benchmark/requirements.csv").set_index("requirement_id")
pd.DataFrame([{"requirement_id": r.requirement_id,
               "expected": benchmark.loc[r.requirement_id, "verdict"],
               "predicted": r.audit.verdict if r.audit else None,
               "expected_clause_retrieved": benchmark.loc[r.requirement_id, "swe_id"] in {c.swe_id for c in r.retrieved}}
              for r in results])

  requirement_id expected predicted  expected_clause_retrieved
0    NASA-SR-001    Meets     Meets                       True
1    NASA-SR-002      Gap       Gap                       True
2    NASA-SR-003    Meets     Meets                       True
3    NASA-SR-004    Meets     Meets                       True
4    NASA-SR-005  Partial       Gap                       True
5    NASA-SR-006    Meets     Meets                       True
6    NASA-SR-007    Meets     Meets                       True
7    NASA-SR-008      Gap   Partial                       True
8    NASA-SR-009    Meets     Meets                       True
9    NASA-SR-010    Meets     Meets                       True

In [6]:
from scripts.summarize_rag_run import summarize

cases = pd.read_csv(ROOT / "data/benchmark/requirements.csv").to_dict(orient="records")
comparisons = []
for label, filename in [("Original 10", "baseline.json"),
                        ("Updated 10", "demo.json"),
                        ("Full 50", "audit-results.json")]:
    saved = json.loads((ROOT / "outputs/rag" / filename).read_text())
    summary = summarize(saved, cases)
    comparisons.append({"run": label, "total": summary["total"], **summary["counts"]})
pd.DataFrame(comparisons)

,run,total,valid_output,expected_clause_retrieved,expected_clause_cited,verdict_matches,grounded_verdict_matches
0,Original 10,10,7,7,6,5,4
1,Updated 10,10,10,10,9,8,7
2,Full 50,50,50,50,48,37,35

## Interpretation

These examples were used during development and error analysis. They are not an independent holdout. The notebook retains the original ten-example run alongside the updated ten-example slice and the full 50-case run.

A grounded verdict match requires both the expected verdict and the assigned SWE ID in the citations. Correct labels on different clauses do not count as grounded matches. Failures remain in the denominator.

See `docs/rag-quality-check.md` for the measured comparison and remaining cases, and `docs/rag-pipeline.md` for the callable interface, source limitations, and reproduction settings. The team can use these saved outputs in its broader evaluation.