# RAG audit demonstration

Connect FAISS retrieval to a structured NASA requirement audit. The saved outputs come from the local model run documented below. Set `RUN_MODEL = True` to rerun inference. Schema and citation validity do not establish verdict accuracy.

In Colab, choose a GPU runtime, then run all cells. Setup downloads the public repository and installs dependencies. Locally, open this notebook from the checkout after installing `requirements.txt`.

In [1]:
from pathlib import Path
import subprocess
import sys

IN_COLAB = "google.colab" in sys.modules
if IN_COLAB:
    ROOT = Path("/content/Aerospace-1C-compliance-copilot")
    if not ROOT.exists():
        subprocess.run(["git", "clone", "--branch", "alan/rag-audit-pipeline",
                        "https://github.com/Break-Through-Tech/Aerospace-1C-compliance-copilot.git",
                        str(ROOT)], check=True)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", str(ROOT / "requirements.txt")], check=True)
else:
    ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "compliance_copilot").is_dir())
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
print("Repository ready")

Repository ready

In [2]:
RUN_MODEL = False
REPORT = ROOT / "outputs/rag/demo.json"
if RUN_MODEL:
    REPORT = ROOT / "outputs/rag/notebook-run.json"
    REPORT.unlink(missing_ok=True)
    completed = subprocess.run([sys.executable, str(ROOT / "scripts/run_rag_demo.py"),
                                "--output", str(REPORT)], cwd=ROOT)
    if not REPORT.exists():
        raise RuntimeError("Model run failed before writing results; inspect the output above")
    if completed.returncode:
        print("The run contains audit errors; inspect them below.")
print("Displaying a new run" if RUN_MODEL else "Displaying the saved model run")

Displaying the saved model run

In [3]:
import json
import pandas as pd
from compliance_copilot.schemas import AuditResult

report = json.loads(REPORT.read_text())
results = [AuditResult.model_validate(row) for row in report["results"]]
print(json.dumps(report["config"], indent=2))
pd.DataFrame([{"requirement_id": r.requirement_id, "status": r.status,
               "verdict": r.audit.verdict if r.audit else None,
               "cited_swe_ids": ", ".join(c.swe_id for c in r.audit.citations) if r.audit else "",
               "error": r.error_code} for r in results])

{
  "model": "Qwen/Qwen2.5-3B-Instruct",
  "model_revision": "aa8e72537993ba99e69dfaafa59ed015b17504d1",
  "embedding_model": "sentence-transformers/all-MiniLM-L6-v2",
  "embedding_revision": "1110a243fdf4706b3f48f1d95db1a4f5529b4d41",
  "top_k": 5,
  "do_sample": false,
  "max_new_tokens": 768,
  "device": "mps",
  "python": "3.12.13",
  "packages": {
    "torch": "2.14.1",
    "transformers": "4.57.6",
    "sentence-transformers": "5.7.0",
    "faiss-cpu": "1.15.1",
    "pydantic": "2.13.5"
  }
}

,requirement_id,status,verdict,cited_swe_ids,error
0,NASA-SR-001,error,None,,invalid_output
1,NASA-SR-002,error,None,,invalid_output
2,NASA-SR-003,ok,Gap,SWE-052,None
3,NASA-SR-004,ok,Meets,"SWE-050, SWE-053, SWE-042",None
4,NASA-SR-005,error,None,,invalid_output
5,NASA-SR-006,ok,Meets,SWE-055,None
6,NASA-SR-007,ok,Meets,SWE-057,None
7,NASA-SR-008,ok,Gap,"SWE-002, SWE-042, SWE-208, SWE-040, SWE-216",None
8,NASA-SR-009,ok,Meets,"SWE-135, SWE-201",None
9,NASA-SR-010,ok,Gap,SWE-062,None

In [4]:
for result in results:
    print(result.requirement_id)
    print(result.requirement_text)
    if result.audit:
        print(result.audit.verdict + ": " + result.audit.reasoning)
        for citation in result.audit.citations:
            clause = next(c for c in result.retrieved if c.swe_id == citation.swe_id)
            print(citation.swe_id, citation.section, repr(citation.quote))
            print(clause.source_url)
    else:
        print(result.error_code, result.error_message)
    print()

NASA-SR-001
The NASA Project Manager shall develop, maintain, and execute a Software Development Plan and a Software Security Plan covering the full software life cycle from requirements through retirement, addressing every applicable requirement of NPR 7150.2D per the approved Requirements Mapping Matrix.
invalid_output Model response failed the audit JSON schema

NASA-SR-002
The NASA software shall meet performance expectations as determined by the development team prior to delivery.
invalid_output Model response failed the audit JSON schema

NASA-SR-003
For Class B software, the NASA Project Manager shall perform, record, and maintain bidirectional traceability between higher-level and software requirements, software requirements and system hazards, software requirements and design components, design components and code, software requirements and software verifications, and software requirements and software non-conformances. The traceability records shall be updated within five business days of a requirement change.
Gap: The requirement specifies bidirectional traceability between various software elements, which is covered by the clause SWE-052. However, the requirement also mentions updating traceability records within five business days of a requirement change, which is not addressed in the clause. Additionally, the clause does not mention the update frequency of the traceability records.
SWE-052 3.12.1 '3.12.1 The project manager shall perform, record, and maintain bi-directional traceability between the following software elements: [SWE-052] Table 1. Bi-directional traceability by software classification Bi-directional Traceability Class A, B, and C Class D Class F Higher-level requirements to the software requirements X X Software requirements to the system hazards X X Software requirements to the software design components X Software design components to the software code X Software requirements to the software verification(s) X X X Software requirements to the software non-conformances X X X'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=31

NASA-SR-004
The NASA Project Manager shall establish, capture, record, approve, and maintain software requirements, including requirements for the reused GPS ephemeris library, in the DOORS requirements repository as part of the project technical specification.
Meets: The requirement is fully covered by the selected clauses. It meets the obligations of establishing, capturing, recording, approving, and maintaining software requirements (SWE-050), tracking and managing changes to the software requirements (SWE-053), and providing electronic access to the source code (SWE-042). The requirement also mentions the reuse of GPS ephemeris library, which is implicitly covered under the general requirements for software components (SWE-050).
SWE-050 4.1.2 'The project manager shall establish, capture, record, approve, and maintain software requirements, including requirements for COTS, GOTS, MOTS, OSS, or reused software components, as part of the technical specification.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=32
SWE-053 4.1.5 'The project manager shall track and manage changes to the software requirements.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=32
SWE-042 3.1.10 'The project manager shall require the software developer(s) to provide NASA with electronic access to the source code developed for the project in a modifiable format.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=21

NASA-SR-005
Changes to NASA software requirements shall be logged in the issue tracker by the engineer making the change.
invalid_output Model response failed the audit JSON schema

NASA-SR-006
The NASA Project Manager shall perform requirements validation with the customer, including scenario-based walkthroughs and a requirements review board, to confirm the software will perform as intended in the lunar relay operational environment prior to baselining.
Meets: The requirement covers the mandatory aspects of performing requirements validation with the customer, including scenario-based walkthroughs and a requirements review board, which aligns with the clause SWE-055. This ensures the software will perform as intended in the customer environment.
SWE-055 4.1.7 '4.1.7 The project manager shall perform requirements validation to ensure that the software will perform as intended in the customer environment.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=32

NASA-SR-007
The NASA Project Manager shall transform the approved software requirements into a recorded software architecture, documented in the Software Architecture Description Document (SADD) and baselined under configuration management prior to detailed design.
Meets: The requirement is fully covered by the clause SWE-057, which mandates that the project manager shall transform the requirements for the software into a recorded software architecture. This requirement aligns with the need to document the software architecture in the Software Architecture Description Document (SADD).
SWE-057 4.2.3 '4.2.3 The project manager shall transform the requirements for the software into a recorded software architecture.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=33

NASA-SR-008
NASA software developers shall write clean, maintainable code following good engineering judgment.
Gap: The provided requirement does not cover any mandatory aspects of the selected clauses. All relevant clauses pertain to leadership and maintenance of initiatives rather than direct guidance on writing clean, maintainable code.
SWE-002 2.1.1.1 'The NASA OCE shall lead and maintain a NASA Software Engineering Initiative to advance software engineering practices.'
https://swehb.nasa.gov/spaces/SITE/pages/123601159/NPR%2B7150.2D
SWE-042 3.1.10 'The project manager shall require the software developer(s) to provide NASA with electronic access to the source code developed for the project in a modifiable format.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=21
SWE-208 2.1.2.2 'The NASA Chief, SMA shall lead and maintain a NASA Software Assurance and Software Safety Initiative to advance software assurance and software safety practices.'
https://swehb.nasa.gov/spaces/SITE/pages/123601159/NPR%2B7150.2D
SWE-040 3.1.9 'The project manager shall require the software developer(s) to provide NASA with software products, traceability, software change tracking information, and nonconformances in electronic format, including software development and management metrics.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=21
SWE-216 2.1.5.14 'The Center Director, or designee, shall ensure that all software listed on the internal software sharing or reuse catalog(s) conforms to NASA software engineering policy and requirements.'
https://swehb.nasa.gov/spaces/SITE/pages/123601159/NPR%2B7150.2D

NASA-SR-009
The NASA Project Manager shall use static analysis tools during development and testing to analyze code for defects, software security, code coverage, and software complexity, and shall track identified findings to closure in the defect tracking system.
Meets: The requirement covers all mandatory aspects of the selected clause(s). It specifies the use of static analysis tools to analyze code for defects, software security, code coverage, and software complexity, which aligns with the clause SWE-135. Additionally, it mentions tracking identified findings to closure in the defect tracking system, which is covered by SWE-201.
SWE-135 4.4.4 '4.4.4 The project manager shall use static analysis tools to analyze the code during the development and testing phases to, at a minimum, detect defects, software security, code coverage, and software complexity.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=34
SWE-201 5.5.1 '5.5.1 The project manager shall track and maintain software non-conformances (including defects in tools and appropriate ground software).'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=42

NASA-SR-010
The NASA Project Manager shall unit test each software code unit against its detailed design prior to integration, and shall record unit test results in the test management system.
Gap: The requirement mentions unit testing each software code unit against its detailed design and recording unit test results, which is covered by SWE-062. However, it does not mention the recording of unit test results in a test management system, which is not addressed by any of the provided clauses.
SWE-062 4.4.5 'The project manager shall unit test the software code.'
https://explorers.larc.nasa.gov/APSMEX26/SMEX/pdf_files/NASA21_NPR_7150_2D.pdf#page=34

In [5]:
# Labels are joined only after inference, never supplied to the pipeline.
benchmark = pd.read_csv(ROOT / "data/benchmark/requirements.csv").set_index("requirement_id")
pd.DataFrame([{"requirement_id": r.requirement_id,
               "expected": benchmark.loc[r.requirement_id, "verdict"],
               "predicted": r.audit.verdict if r.audit else None,
               "expected_clause_retrieved": benchmark.loc[r.requirement_id, "swe_id"] in {c.swe_id for c in r.retrieved}}
              for r in results])

  requirement_id expected predicted  expected_clause_retrieved
0    NASA-SR-001    Meets      None                      False
1    NASA-SR-002      Gap      None                      False
2    NASA-SR-003    Meets       Gap                       True
3    NASA-SR-004    Meets     Meets                       True
4    NASA-SR-005  Partial      None                       True
5    NASA-SR-006    Meets     Meets                       True
6    NASA-SR-007    Meets     Meets                       True
7    NASA-SR-008      Gap       Gap                      False
8    NASA-SR-009    Meets     Meets                       True
9    NASA-SR-010    Meets       Gap                       True

## Interpretation

This small run demonstrates retrieval, generation, and validation. Expected verdicts are shown for inspection, not as a performance estimate. Review incorrect clause selection and incomplete source text separately from schema failures. The full 50-case evaluation belongs to Task 3.

See `docs/rag-pipeline.md` for the reusable callable interface, errors, source limitations, and reproduction settings.